### ISSUE TITLE
Try to use pyorient driver with python 2.6.6. Get SyntaxError: invalid syntax.

### ISSUE THREAD

**Issue by juriskrumins** [orientechnologies/pyorient#23]
```
[root@host juriskr]# python --version
Python 2.6.6
[root@host juriskr]# cat o.py
import sys
sys.path.append("/home/juriskr/pyorient-1.4.5")
import pyorient
client = pyorient.OrientDB("localhost", 2424)
session_id = client.connect("root", "root")
[root@host juriskr]# python o.py
Traceback (most recent call last):
  File "o.py", line 3, in <module>
    import pyorient
  File "/home/juriskr/pyorient-1.4.5/pyorient/__init__.py", line 8, in <module>
    from .scripts import Scripts
  File "/home/juriskr/pyorient-1.4.5/pyorient/scripts.py", line 59
    args = {k:v for k,v in args.items() if k in param_defaults.keys()}
                  ^
SyntaxError: invalid syntax
[root@host juriskr]#
```

**Comment by Ostico** [comment]
Python 2.6 is not supported.
