### ISSUE TITLE
doesn't support OrientDB 2.1.2

### ISSUE THREAD

**Issue by michael-go** [orientechnologies/pyorient#7]
`client.connect()` throws:
`
pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 32 is not supported yet by this client.
`

**Comment by peddadap** [comment]
yes, I'm getting similar kind of results 2.1.2 Enterprise Edition
pydev debugger: starting (pid: 64191)
Traceback (most recent call last):
  File "/Users/Pavan/Downloads/Eclipse.app/Contents/Eclipse/plugins/org.python.pydev_4.3.0.201508182223/pysrc/pydevd.py", line 2283, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "/Users/Pavan/Downloads/Eclipse.app/Contents/Eclipse/plugins/org.python.pydev_4.3.0.201508182223/pysrc/pydevd.py", line 1709, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/Pavan/Documents/workspace/neo4j/import-handlers/orient_db_contact.py", line 6, in <module>
    client.connect("admin", "admin")
  File "/Library/Python/2.7/site-packages/pyorient/orient.py", line 210, in connect
    return self.get_message("ConnectMessage") \
  File "/Library/Python/2.7/site-packages/pyorient/orient.py", line 355, in get_message
    return _Message(self._connection)\
  File "/Library/Python/2.7/site-packages/pyorient/messages/connection.py", line 18, in __init__
    super( ConnectMessage, self ).__init__(_orient_socket)
  File "/Library/Python/2.7/site-packages/pyorient/messages/base.py", line 40, in __init__
    sock.get_connection()
  File "/Library/Python/2.7/site-packages/pyorient/orient.py", line 41, in get_connection
    self.connect()
  File "/Library/Python/2.7/site-packages/pyorient/orient.py", line 64, in connect
    " is not supported yet by this client.", [])
pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 32 is not supported yet by this client.

**Comment by Ostico** [comment]
Scheduled for saturday

**Comment by jwogrady** [comment]
@Ostico any updates. Running into the same issue.

**Comment by Ostico** [comment]
Closed
